# Generated by Django 5.2.8 on 2025-12-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_groups_alter_user_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_method",
            new_name="method",
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payment",
            name="sessions_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="id сессии"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
    ]
