# Generated by Django 5.2.8 on 2025-12-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_payment_amount_payment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")], default="transfer", max_length=8
            ),
        ),
    ]
