# Generated by Django 5.2.8 on 2025-12-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(default=0, verbose_name="Сумма оплаты"),
        ),
    ]
