# Generated by Django 5.2.8 on 2025-12-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payment_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="sessions_id",
            new_name="session_id",
        ),
    ]
