# Generated by Django 5.2.8 on 2025-11-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Название курса")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="lms/course/preview", verbose_name="Превью курса"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание курса")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Название урока")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="lms/lesson/preview", verbose_name="Превью урока"
                    ),
                ),
                ("video_link", models.URLField(blank=True, null=True, verbose_name="Ссылка на видео урока")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
